### ISSUE TITLE
Different event id – Uuid/Guid – byte order

### ISSUE THREAD

**Issue by larsschumacher** [YoEight/eventstore-rs#43]
Hi @YoEight,

Great job!

I have a problem with the event id: I am sending an event with the id `3cd53ad8-54d3-4f4a-b116-1f09957af330`. But in the eventstore ui the id `d83ad53c-d354-4a4f-b116-1f09957af330` is displayed and also the .NET client and curl return the wrong event id.
The reason for this is the "strange" byte order of the .NET Guid implementation.

```rust
let event_id = Uuid::parse_str("3cd53ad8-54d3-4f4a-b116-1f09957af330").unwrap();
    
println!("{:?}", event_id.as_bytes());

> [60, 213, 58, 216, 84, 211, 79, 74, 177, 22, 31, 9, 149, 122, 243, 48]
```

```csharp
var event_id = new Guid("3cd53ad8-54d3-4f4a-b116-1f09957af330");

Console.WriteLine("[{0}]", string.Join(", ", event_id.ToByteArray()));

> [216, 58, 213, 60, 211, 84, 74, 79, 177, 22, 31, 9, 149, 122, 243, 48]
```

The first 4 bytes are in reverse order. 
Bytes 5 and 6, as well as bytes 7 and 8 are swapped.
The remaining 8 bytes are in the correct order.

**Comment by YoEight** [comment]
Hi @larsschumacher,

I confirm that behaviour and  I should have been more explicit about that shortcoming, but in practice, it doesn't prevent the server nor the client from working correctly.

Let's fix it 💪 !

**Comment by YoEight** [comment]
Fixed

**Comment by YoEight** [comment]
Hi @larsschumacher the release that includes your patch is available on [crates.io]. Thanks again for your contribution!

[crates.io]: https://crates.io/crates/eventstore/0.7.2
