### ISSUE TITLE
Questions about connection's state

### ISSUE THREAD

**Issue by chapa** [YoEight/eventstore-rs#53]
Hello (again),

I'm trying to set up a pool of `eventstore::Connection` by creating an adapter for the crate [`l337`](https://docs.rs/l337/0.4.1/l337/) and I have some questions about how to do certain things with this library (`eventstore`).
I hope my questions and remarks will be relevant, it's been just a few weeks since I started to play with Rust so be lenient :slightly_smiling_face:

First of all, I find pretty strange that `ConnectionBuilder::single_node_connection()` and `ConnectionBuilder::cluster_nodes_through_gossip_connection()` directly return a `Connection` and not a `Result<Connection, _>`.
They are async functions so it suggests that they are trying to contact the EventStore server, which may be unreachable so it would make more sense to get a `Result`.

For the need of the adapter, I need a way to know if the connection is healthy.
How I'm doing it currently is by making this request : `connection.read_all().max_count(0).execute().await`.
Do you think there is a better (more performant) way to check if the connection is (still) alive ?

Wouldn't it be possible to get the connection state in a synchronous fashion ? Maybe it's another subject than my previous question.
I think of a state that we could check at any time (a method on `Connection` ?), which would be updated when the server stops responding for example, or when a request failed.
I don't know if you can be informed in any way when the connection with the server is lost, to update such a state ?

There is one last thing I wanted to mention, it doesn't have much to do with the rest but I noticed some logs like `HEARTBEAT TIMEOUT` or `Persistent subscription lost connection` in the EventStore server when calling `connection.shutdown().await`, that makes me think to a badly closed connection.
Here are the logs in question :
```
# The first request is made

[00001,05,21:53:11.511] External TCP connection accepted: [Normal, 172.17.0.1:47828, L172.17.0.2:1113, {b3d1959c-4a64-42d9-baa3-aac9d7f13bbf}].
[00001,26,21:53:11.511] Connection '"external-normal"' ({b3d1959c-4a64-42d9-baa3-aac9d7f13bbf}) identified by client. Client connection name: '"ES-37f46d53-dd9b-4c66-bddb-b7030049fd24"', Client version: V2.

# The `.shutdown().await` is called, followed by `sleep(Duration::from_secs(10))`, but the following logs appears only 5 seconds after

[00001,14,21:53:16.524] Closing connection '"external-normal"":ES-37f46d53-dd9b-4c66-bddb-b7030049fd24"' [172.17.0.1:47828, L172.17.0.2:1113, {b3d1959c-4a64-42d9-baa3-aac9d7f13bbf}] cleanly." Reason: HEARTBEAT TIMEOUT at msgNum 3"
[00001,14,21:53:16.525] ES "TcpConnection" closed [21:53:16.525: N172.17.0.1:47828, L172.17.0.2:1113, {b3d1959c-4a64-42d9-baa3-aac9d7f13bbf}]:Received bytes: 134, Sent bytes: 204
[00001,14,21:53:16.525] ES "TcpConnection" closed [21:53:16.526: N172.17.0.1:47828, L172.17.0.2:1113, {b3d1959c-4a64-42d9-baa3-aac9d7f13bbf}]:Send calls: 4, callbacks: 4
[00001,14,21:53:16.525] ES "TcpConnection" closed [21:53:16.526: N172.17.0.1:47828, L172.17.0.2:1113, {b3d1959c-4a64-42d9-baa3-aac9d7f13bbf}]:Receive calls: 4, callbacks: 3
[00001,14,21:53:16.525] ES "TcpConnection" closed [21:53:16.526: N172.17.0.1:47828, L172.17.0.2:1113, {b3d1959c-4a64-42d9-baa3-aac9d7f13bbf}]:Close reason: [Success] "HEARTBEAT TIMEOUT at msgNum 3"
[00001,14,21:53:16.525] Connection '"external-normal"":ES-37f46d53-dd9b-4c66-bddb-b7030049fd24"' [172.17.0.1:47828, {b3d1959c-4a64-42d9-baa3-aac9d7f13bbf}] closed: Success.
[00001,20,21:53:16.528] Persistent subscription lost connection from 172.17.0.1:47828
```
Maybe it's completely normal, but I'm not sure :thinking:

Thank you (again) for taking the time to answer my questions.

**Comment by YoEight** [comment]
Hello,

> First of all, I find pretty strange that ConnectionBuilder::single_node_connection() and ConnectionBuilder::cluster_nodes_through_gossip_connection() directly return a Connection and not a Result<Connection, _>.
They are async functions, so it suggests that they are trying to contact the EventStore server, which may be unreachable so it would make more sense to get a Result.

Those functions don't return a connection (like a socket connection). It is doubtful there is an active TCP connection when those functions return (hence why those can't fail at that time). The `Connection` type is a queue that sends messages to a connection state-machine. That connection state-machine could have had multiple different TCP connections, not at the same time though, without you knowing it (in a user point of view). A TCP Event Store connection stays open all the time.

That connection state-machine is tracking the healthiness of a TCP connection by using a heartbeat protocol (similar to the one used by the server) in case the server connection is lost or if the server takes too much time to respond. If it happens, then the state-machine starts a new TCP connection (transparent for the user). When in a cluster mode connection, the state-machine will pick a node among the cluster (based on some user preferences and which node failed last time)

That connection state-machine is also a command bookkeeper:
* Tracks when a command takes too much time and retries based on user preferences.
* Postpones commands if there is no active connection yet, retries them once a connection is available.

Everything is transparent to the user that is not exposed to that complexity (part of the EventStore TCP protocol) and only has a single and thread-safe reference to the connection state machine.

> Wouldn't it be possible to get the connection state in a synchronous fashion ?

Not possible without blocking the connection state machine and decreasing the overall performance.

> There is one last thing I wanted to mention, it doesn't have much to do with the rest but I noticed some logs like HEARTBEAT TIMEOUT or Persistent subscription lost connection in the EventStore server when calling connection.shutdown().await, that makes me think to a badly closed connection.

While I don't exclude the possibility that something could have been left out open, it's improbable. When shutting down, the state-machine blocks further new command and prevents existing one from sending new packages. The state machine completes every pending command (like persistent subscriptions) before closing the TCP connection. I would investigate your scenario.

**Comment by YoEight** [comment]
Next time, please consider the [Discord] server for questions too.

[Discord]: https://discord.gg/x7q37jJ

**Comment by chapa** [comment]
Thank you for your detailed answers.
I still have some questions but I'll go to the Discord server and ask them as you advise :wink:
